In [2]:
import time

In [3]:
a = list(range(1000000))
b = list(range(1000000))

start_p = time.perf_counter()
c = [x + y for x, y in zip(a, b)]
end_p = time.perf_counter()
total_p = end_p - start_p
print("Python:", total_p)

Python: 0.23000290000345558


In [5]:
import numpy as np

In [6]:
a_np = np.array(a)
b_np = np.array(b)

start_n = time.perf_counter()
c_np = a_np + b_np
end_n = time.perf_counter()
total_n = end_n - start_n
print("NumPy:", total_n)

NumPy: 0.006372000032570213


In [7]:
print(f"Numpy is faster than python by : {total_p/total_n:.2f}")

Numpy is faster than python by : 24.52


# Numpy

Python lists are : 
 - Flexible but slow for numerical operations
 - Not designed for matrix math or
 - Does not support vectorised operation
 - Are memory inefficient for large numerical data

Why use numpy?
- Fast than pure python for numerical computation
- Vectorized operation (no explicit loops)
- Broadcasting (operate on arrays of different shape)
- Memory efficient
- Comes with powerful linear algebra, random tools etc

Use of numpy :
- Scientific python

In [9]:
# !pip install numpy

In [10]:
import numpy as np

# creating arrays in numpy

### 1. np.array()

In [11]:
arr_1 = np.array([1,2,3])

print(arr_1)
print(type(arr_1))

[1 2 3]
<class 'numpy.ndarray'>


In [21]:
arr_1

array([1, 2, 3])

In [16]:
type(arr_1[0])

numpy.int64

In [12]:
arr_2 = np.array([[1,2,3], [4,5,6]])

print(arr_2)

[[1 2 3]
 [4 5 6]]


In [22]:
arr_2[0]

array([1, 2, 3])

In [23]:
arr_2[0][2]

np.int64(3)

In [24]:
arr_2[1][2]

np.int64(6)

In [13]:
arr_3 = np.array([1,2,3, "hello"])

print(arr_3)
print(type(arr_3))

['1' '2' '3' 'hello']
<class 'numpy.ndarray'>


In [14]:
print(type(arr_3[1]))

<class 'numpy.str_'>


In [15]:
arr_4 = np.array([1,2,3], dtype=np.int8)
print(type(arr_4))

<class 'numpy.ndarray'>


In [16]:
type(arr_4[0])

numpy.int8

In [21]:
arr_5 = np.array([1,2,3, "hello"])

In [23]:
arr_5

array(['1', '2', '3', 'hello'], dtype='<U21')

In [19]:
arr_6 = np.array([1,2,3, "10"], dtype=np.float16)

In [20]:
arr_6

array([ 1.,  2.,  3., 10.], dtype=float16)

In [ ]:
# arrays can have elements with only one data type

### 2. np.arange(start, stop, step)

In [24]:
list(range(1, 11, 2))

[1, 3, 5, 7, 9]

In [25]:
b = np.arange(1, 11, 2)

In [26]:
b

array([1, 3, 5, 7, 9])

### 3. np.linspace(start, stop, num=x)
stop - inclusive

In [27]:
np_linspace_1 = np.linspace(1,100,4)
print(np_linspace_1)
print(type(np_linspace_1))

[  1.  34.  67. 100.]
<class 'numpy.ndarray'>


In [28]:
np_linspace_2 = np.linspace(1,10,10)
print(np_linspace_2)
print(type(np_linspace_2))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>


In [29]:
for num in np.linspace(1,10,10):
    # print(type(num))
    print(num)
    # print(type(int(num)))
    # print("=================")

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [30]:
for num in np.linspace(1,10,10, dtype=np.int8):
    print(num)

1
2
3
4
5
6
7
8
9
10


### 4. np.zeros(shape)

shape -> shape of matrix

In [31]:
npz_1 = np.zeros(5)

In [32]:
npz_1

array([0., 0., 0., 0., 0.])

In [33]:
npz_2 = np.zeros((5,5), dtype=np.int8)
print(npz_2)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [50]:
npz_2 = np.zeros((5,5))
print(npz_2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [34]:
npz_3 = np.zeros((5,5,5))
print(npz_3)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [35]:
npz_3.ndim

3